services:
  icecream-worker:
    build: .
    container_name: icecream_worker_node
    restart: unless-stopped
    network_mode: "host"
    privileged: true    
    environment:
      - TERM=xterm-256color
      - ICECC_SCHEDULER_HOST=192.168.1.6
      - ICECC_NETNAME=icecream
      - ICECC_MAX_JOBS=
    tty: true
    stdin_open: true